
services:
  rstsql:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_URI=postgresql://test:01234@postgres:5432/test
    volumes:
      - ./test_dsl:/DSL
  
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=01234
      - POSTGRES_DB=test
    ports:
      - 5432:5432
